#!/bin/sh
# Install aptai. POSIX sh; no build step, no pip, no network access.
#
#   sudo ./scripts/install.sh                 # install
#   sudo ./scripts/install.sh --enable-timer  # install and start the daily timer
#   sudo PREFIX=/usr ./scripts/install.sh     # install under /usr instead

set -eu

PREFIX="${PREFIX:-/usr/local}"
CONFDIR="${CONFDIR:-/etc/aptai}"
LOGDIR="${LOGDIR:-/var/log/aptai}"
STATEDIR="${STATEDIR:-/var/lib/aptai}"
UNITDIR="${UNITDIR:-/etc/systemd/system}"
PYTHON="${PYTHON:-/usr/bin/python3}"
LIBDIR="$PREFIX/lib/aptai"
BINDIR="$PREFIX/bin"

ENABLE_TIMER=0
for arg in "$@"; do
    case "$arg" in
        --enable-timer) ENABLE_TIMER=1 ;;
        -h|--help)
            sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "install.sh: unknown option: $arg" >&2; exit 2 ;;
    esac
done

SRC="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

die() { echo "install.sh: $*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || die "must be run as root (try: sudo $0)"
[ -x "$PYTHON" ] || die "$PYTHON not found; install the python3 package"

"$PYTHON" - <<'PY' || die "aptai needs Python 3.11 or newer (tomllib)"
import sys
raise SystemExit(0 if sys.version_info >= (3, 11) else 1)
PY

command -v apt-get >/dev/null 2>&1 || echo "install.sh: warning: apt-get not found; this is a Debian/Ubuntu tool" >&2

echo "installing the package to $LIBDIR"
install -d -m 0755 "$LIBDIR" "$LIBDIR/aptai" "$BINDIR"
rm -f "$LIBDIR/aptai"/*.py
for f in "$SRC"/aptai/*.py; do
    install -m 0644 "$f" "$LIBDIR/aptai/"
done
rm -rf "$LIBDIR/aptai/__pycache__"

echo "installing the launcher to $BINDIR/aptai"
cat > "$BINDIR/aptai" <<LAUNCHER
#!$PYTHON -Es
# Generated by aptai install.sh -- edit $LIBDIR/aptai instead.
import sys

sys.path.insert(0, "$LIBDIR")

from aptai.cli import main

sys.exit(main())
LAUNCHER
chmod 0755 "$BINDIR/aptai"

echo "creating $CONFDIR, $LOGDIR and $STATEDIR"
install -d -m 0755 "$CONFDIR"
install -d -m 0750 "$LOGDIR" "$STATEDIR"

if [ -f "$CONFDIR/config.toml" ]; then
    install -m 0644 "$SRC/config/aptai.toml" "$CONFDIR/config.toml.new"
    echo "kept the existing $CONFDIR/config.toml (new version: $CONFDIR/config.toml.new)"
else
    install -m 0644 "$SRC/config/aptai.toml" "$CONFDIR/config.toml"
    echo "wrote $CONFDIR/config.toml"
fi

if [ ! -f "$CONFDIR/env" ]; then
    install -m 0600 "$SRC/config/env.example" "$CONFDIR/env"
    echo "wrote $CONFDIR/env -- put your ANTHROPIC_API_KEY there (mode 0600)"
fi

if [ -d "$UNITDIR" ]; then
    echo "installing systemd units to $UNITDIR"
    sed "s#/usr/local/bin/aptai#$BINDIR/aptai#" "$SRC/systemd/aptai.service" > "$UNITDIR/aptai.service"
    chmod 0644 "$UNITDIR/aptai.service"
    install -m 0644 "$SRC/systemd/aptai.timer" "$UNITDIR/aptai.timer"
    if command -v systemctl >/dev/null 2>&1; then
        systemctl daemon-reload || true
        if [ "$ENABLE_TIMER" = "1" ]; then
            systemctl enable --now aptai.timer
            echo "aptai.timer enabled"
        fi
    fi
fi

echo
echo "aptai installed. Next steps:"
echo "  1. editor $CONFDIR/env          # ANTHROPIC_API_KEY=sk-ant-..."
echo "  2. editor $CONFDIR/config.toml  # webhook URLs, mode, limits"
echo "  3. aptai check                  # preflight, API key and webhook check"
echo "  4. aptai diagnose               # exactly what would be uploaded"
echo "  5. aptai run --dry-run          # a full run that changes nothing"
echo "  6. systemctl enable --now aptai.timer"
